/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache assets generated by webpack
precacheAndRoute(self.__WB_MANIFEST);

// Cache HTML, CSS, and JS files with the NetworkFirst strategy
registerRoute(
  /\.(?:html|css|js)$/,
  new NetworkFirst({
    cacheName: 'static-resources',
  })
);

// Cache images with the CacheFirst strategy and expiration
registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg)$/,
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);
